Explicit links to the important whitepaper and blog for ML Platform
aws-samples/awesome-sagemaker pull request #15
Opened 2023-02-07 13:25 UTC by ivan-khvostishkov

Explicit links to the important whitepaper and blog mentioned in "Setting up secure, well-governed machine learning environments"

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Please make sure your entry is respecting the format defined in the [contribution guidelines](./../CONTRIBUTING.md).

## Topic Area

Please select the area where you want to include the content.

- [X] Getting Started
- [ ] Building ML Models
- [ ] Deploying ML Models
- [ ] MLOps
- [ ] Low Code/ No Code ML
- [ ] ML Governance
- [ ] Responsible AI
- [ ] Audio
- [ ] Computer Vision
- [ ] NLP
- [ ] R
- [ ] Learning SageMaker

## Content Type

- [X] Blog
- [ ] Code
- [X] Docs
- [ ] Video
- [ ] Workshop

2023-02-15 15:54 UTC, brunopistone requested changes
Hello @ivan-khvostishkov , can you please do the following changes?

1. [Docs] [Build a Secure Enterprise Machine Learning Platform on AWS] in Getting Started, under ML Platform Setup: Please avoid wrong indentation
2. [Docs][AWS accounts](https://docs.aws.amazon.com/whitepapers/latest/build-secure-enterprise-ml-platform/aws-accounts.html) in Getting Started, under ML Platform Setup: Please avoid wrong indentation: I see it as relevant topic to be highlighted in the list
3. [Blog] [Building a Secure Cross-Account Continuous Delivery Pipeline](https://aws.amazon.com/blogs/devops/aws-building-a-secure-cross-account-continuous-delivery-pipeline/) in the section MLOps

Thank you

2023-02-24 07:18 UTC, ivan-khvostishkov commented
Hi, @brunopistone ! I've fixed the indent. Please, check.

2023-02-24 07:27 UTC, ivan-khvostishkov commented
Hi, @brunopistone ! I've made the changes. Please, check!

2023-02-24 08:03 UTC, brunopistone approved these changes

2023-02-24 08:03 UTC, merged